author: Tobe O <thosakwe@gmail.com>
description: Dart bindings for Phaser CE 2.9.4.
homepage: https://github.com/thosakwe/dart_phaser
name: phaser
version: 2.9.4-beta
dependencies: 
  func: ^0.1.0
  js: ^0.6.1
dev_dependencies:
  build_runner: ^0.6.1
  build_test: ^0.9.3
  where: ^3.0.0
environment:
  sdk: ">=1.19.0"
