author: "Tobe O <thosakwe@gmail.com>"
description: "Dart bindings for Phaser 2.6.2."
environment:
  sdk: ">=1.19.0"
homepage: "https://github.com/thosakwe/dart_phaser"
name: "phaser"
version: "3.0.0-dev"
dependencies: 
  angular2: "^2.2.0"
  angular2_components: "^0.2.0"
  js: "^0.6.1"
dev_dependencies: 
  browser: "^0.10.0+2"
  dart_to_js_script_rewriter: "^1.0.2"
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- "dart_to_js_script_rewriter"
